/**
 * Helpers around MongoDB GridFS for blog images. We store optimized variants
 * (avif/webp/jpg, multiple widths) for one logical image as separate GridFS
 * files all sharing the same `parentId` in their metadata.
 */
// Server-only by use, not by import guard — see comment in lib/gemini.ts.
import { GridFSBucket, ObjectId, type Db } from "mongodb";
import { getMongoDb } from "./mongo-client";

const BUCKET = "blogImages";

let cachedBucket: { db: Db; bucket: GridFSBucket } | null = null;

async function getBucket(): Promise<GridFSBucket> {
  if (cachedBucket) return cachedBucket.bucket;
  const db = await getMongoDb();
  const bucket = new GridFSBucket(db, { bucketName: BUCKET });
  cachedBucket = { db, bucket };
  return bucket;
}

export type ImageMetadata = {
  /** Logical group this variant belongs to (covers + variants share this). */
  parentId: string;
  /** Identifier for the variant: "original", "1200.webp", "800.avif", etc. */
  variant: string;
  /** Pixel width of this variant. */
  width?: number;
  /** Pixel height of this variant. */
  height?: number;
  /** "image/webp", "image/avif", "image/jpeg", ... */
  contentType: string;
  /** Optional alt text for the canonical image. */
  alt?: string;
  /** Optional prompt used when generated by AI. */
  prompt?: string;
  /** Optional logical use ("post-cover", "post-inline", "testimonial-avatar", ...) */
  use?: string;
  /** Optional: id of the post this image belongs to. */
  postId?: string;
};

export async function uploadImageVariant(
  buffer: Buffer,
  filename: string,
  metadata: ImageMetadata,
): Promise<string> {
  const bucket = await getBucket();
  return new Promise<string>((resolve, reject) => {
    const stream = bucket.openUploadStream(filename, {
      metadata,
    });
    stream.on("error", reject);
    stream.on("finish", () => resolve(stream.id.toString()));
    stream.end(buffer);
  });
}

export async function findFileById(id: string) {
  const bucket = await getBucket();
  let _id: ObjectId;
  try {
    _id = new ObjectId(id);
  } catch {
    return null;
  }
  const cursor = bucket.find({ _id });
  const file = await cursor.next();
  return file;
}

export async function streamFile(id: string) {
  const bucket = await getBucket();
  const _id = new ObjectId(id);
  return bucket.openDownloadStream(_id);
}

export async function deleteByParentId(parentId: string): Promise<number> {
  const bucket = await getBucket();
  const cursor = bucket.find({ "metadata.parentId": parentId });
  let count = 0;
  while (await cursor.hasNext()) {
    const file = await cursor.next();
    if (!file) break;
    await bucket.delete(file._id);
    count++;
  }
  return count;
}
