import mongoose, { Schema, type InferSchemaType, type Model } from "mongoose";

const InlineImageSchema = new Schema(
  {
    url: { type: String, required: true, maxlength: 1000 },
    alt: { type: String, maxlength: 300 },
    /** Caption rendered under the image on the public page (optional) */
    caption: { type: String, maxlength: 300 },
    /** Prompt used to generate the image (audit trail). */
    prompt: { type: String, maxlength: 2000 },
    /** Anchor identifier inserted into the body markdown as ![alt](#img:anchor) */
    anchor: { type: String, maxlength: 80 },
    width: { type: Number },
    height: { type: Number },
  },
  { _id: false },
);

const SocialSchema = new Schema(
  {
    twitter: { type: String, maxlength: 1000 },
    linkedin: { type: String, maxlength: 4000 },
    facebook: { type: String, maxlength: 2000 },
    instagram: { type: String, maxlength: 2500 },
  },
  { _id: false },
);

const AiMetaSchema = new Schema(
  {
    /** Last successful AI generation per field, for audit + cost tracking */
    lastGeneratedAt: { type: Date },
    lastModel: { type: String, maxlength: 100 },
    /** Free-form notes — e.g. "draft generated by gemini-2.5-pro at <date>" */
    notes: { type: String, maxlength: 2000 },
  },
  { _id: false },
);

const PostSchema = new Schema(
  {
    slug: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      maxlength: 200,
      index: true,
    },
    title: { type: String, required: true, maxlength: 200 },
    excerpt: { type: String, maxlength: 400 },
    /** Markdown body */
    body: { type: String, required: true, maxlength: 200000 },

    /** Cover (hero) image */
    coverUrl: { type: String, maxlength: 1000 },
    coverAlt: { type: String, maxlength: 300 },
    coverPrompt: { type: String, maxlength: 2000 },

    /** Open Graph / Twitter card image (1200x630). Falls back to coverUrl. */
    seoOgImage: { type: String, maxlength: 1000 },

    tag: { type: String, maxlength: 50 },
    readMin: { type: Number, default: 5 },

    /** Keyword strategy */
    focusKeyword: { type: String, maxlength: 120, index: true },
    keywords: { type: [String], default: [] },

    /** AEO/GEO-friendly takeaways shown in a box near the top of the post */
    keyTakeaways: { type: [String], default: [] },

    /** AEO Q&A block. Each entry becomes a Question in FAQPage schema. */
    faqs: {
      type: [
        new Schema(
          {
            question: { type: String, required: true, maxlength: 300 },
            answer: { type: String, required: true, maxlength: 2000 },
          },
          { _id: false },
        ),
      ],
      default: [],
    },

    /** Inline images referenced from the body markdown */
    inlineImages: { type: [InlineImageSchema], default: [] },

    /** SEO overrides, fall back to title/excerpt when blank */
    seoTitle: { type: String, maxlength: 200 },
    seoDescription: { type: String, maxlength: 300 },

    /** Pre-formatted social posts (per platform) */
    social: { type: SocialSchema, default: () => ({}) },

    /** AI generation audit */
    aiMeta: { type: AiMetaSchema, default: () => ({}) },

    published: { type: Boolean, default: false, index: true },
    publishedAt: { type: Date, index: true },
    authorId: { type: String },
    authorName: { type: String, maxlength: 100 },
  },
  { timestamps: true },
);

PostSchema.index({ published: 1, publishedAt: -1 });
PostSchema.index({ focusKeyword: 1, published: 1 });

export type PostDoc = InferSchemaType<typeof PostSchema> & {
  _id: mongoose.Types.ObjectId;
};

export const Post: Model<PostDoc> =
  (mongoose.models.Post as Model<PostDoc>) ||
  mongoose.model<PostDoc>("Post", PostSchema);
